apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "postgres"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command: ["cat", "/proc/1/status"]
          initialDelaySeconds: 30
          periodSeconds: 15
