apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vote-pdb
  namespace: prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vote
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: result-pdb
  namespace: prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: result
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker
