apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: flask-app-project

  source:
    repoURL: https://github.com/roshan2152/dodo-assign.git
    targetRevision: main
    path: Task-2/k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Rollback on sync failure
  revisionHistoryLimit: 10

  # Health assessment
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
